import type { TourRole, TourStep } from '@jozeuzz/alltura-ui';

export const TOUR_VERSION = 'v3';

export const onboardingStepsByRole: Record<TourRole, TourStep[]> = {
  admin: [
    {
      id: 'admin-ob-dashboard',
      role: 'admin',
      route: '/admin/dashboard',
      selector: '[data-tour="admin-dashboard-root"]',
      title: 'Panel operativo',
      body: 'Vista central con KPIs de activos, entregas, devoluciones y firmas. Detecta desviaciones antes de que escalen.',
      placement: 'bottom',
    },
    {
      id: 'admin-ob-dashboard-kpis',
      role: 'admin',
      route: '/admin/dashboard',
      selector: '[data-tour="admin-dashboard-kpis"]',
      title: 'Métricas de inventario',
      body: 'Stock disponible, reservado y registros agotados. Las operaciones pendientes de firma se muestran aquí.',
      placement: 'top',
      mobilePlacement: 'bottom',
    },
    {
      id: 'admin-ob-trazabilidad',
      role: 'admin',
      route: '/admin/trazabilidad',
      selector: '[data-tour="admin-dashboard-root"]',
      title: 'Trazabilidad',
      body: 'Movimientos recientes de stock y activos para auditoría operacional. Misma pantalla, vista enfocada en historial.',
      placement: 'bottom',
      mobilePlacement: 'bottom',
    },
    {
      id: 'admin-ob-users',
      role: 'admin',
      route: '/admin/users',
      selector: '[data-tour="admin-users-root"]',
      title: 'Usuarios del sistema',
      body: 'Gestiona las cuentas con acceso a la plataforma. Asigna roles de administrador o supervisor.',
      placement: 'bottom',
      mobilePlacement: 'bottom',
    },
    {
      id: 'admin-ob-trabajadores',
      role: 'admin',
      route: '/admin/trabajadores',
      selector: '[data-tour="admin-trabajadores-root"]',
      title: 'Trabajadores',
      body: 'Personal interno al que se asignan activos. Los trabajadores no son usuarios del sistema por defecto.',
      placement: 'bottom',
      mobilePlacement: 'bottom',
    },
    {
      id: 'admin-ob-bodegas',
      role: 'admin',
      route: '/admin/ubicacion/bodegas',
      selector: '[data-tour="admin-bodegas-root"]',
      title: 'Bodegas',
      body: 'Ubicaciones físicas donde se almacena el inventario. El stock y los activos se mueven entre bodegas y proyectos.',
      placement: 'bottom',
      mobilePlacement: 'bottom',
    },
    {
      id: 'admin-ob-proyectos',
      role: 'admin',
      route: '/admin/ubicacion/proyectos',
      selector: '[data-tour="admin-proyectos-root"]',
      title: 'Proyectos',
      body: 'Frentes de trabajo a los que se asignan equipos y herramientas. Cada activo rastrea su ubicación actual.',
      placement: 'bottom',
      mobilePlacement: 'bottom',
    },
    {
      id: 'admin-ob-articulos',
      role: 'admin',
      route: '/admin/inventario/articulos',
      selector: '[data-tour="admin-inventory-open-article-modal"]',
      title: 'Catálogo de artículos',
      body: 'Define los tipos de activos: EPP, equipos y herramientas. Cada artículo puede tener múltiples unidades físicas.',
      placement: 'bottom',
      mobilePlacement: 'bottom',
    },
    {
      id: 'admin-ob-epp-kpis',
      role: 'admin',
      route: '/admin/inventario/epp',
      selector: '[data-tour="admin-inventory-kpis"]',
      title: 'Inventario EPP',
      body: 'Stock disponible, activos asignados y valor bajo responsabilidad activa. El contador rojo indica agotados o dados de baja.',
      placement: 'bottom',
      mobilePlacement: 'bottom',
    },
    {
      id: 'admin-ob-epp-tab-inventario',
      role: 'admin',
      route: '/admin/inventario/epp',
      title: 'Tab Inventario',
      body: 'Cambiamos al listado de activos individuales. Aquí aparece cada unidad física con su código, estado y ubicación actual.',
      placement: 'center',
      mobilePlacement: 'center',
      demoAction: 'switch-tab:inventario',
    },
    {
      id: 'admin-ob-epp-grid',
      role: 'admin',
      route: '/admin/inventario/epp',
      selector: '[data-tour="admin-inventory-grid"]',
      title: 'Tarjetas de activos',
      body: 'Cada tarjeta es un activo físico único. Haz clic en cualquiera para abrir su perfil completo. Abrimos el primero ahora para recorrerlo juntos.',
      placement: 'top',
      mobilePlacement: 'bottom',
      demoAction: 'open-modal:activo-first',
    },
    {
      id: 'admin-ob-activo-acciones',
      role: 'admin',
      route: '/admin/inventario/epp',
      selector: '[data-tour="activo-modal-acciones"]',
      title: 'Acciones del activo',
      body: 'Panel de operaciones: Entregar asigna el activo a un trabajador con firma digital. Devolver cierra la custodia activa.',
      placement: 'top',
      mobilePlacement: 'bottom',
    },
    {
      id: 'admin-ob-activo-historial',
      role: 'admin',
      route: '/admin/inventario/epp',
      selector: '[data-tour="activo-modal-historial"]',
      title: 'Historial de movimientos',
      body: 'Trazabilidad completa: cada entrega, devolución y cambio de estado con fecha, responsable y destino.',
      placement: 'top',
      mobilePlacement: 'bottom',
    },
    {
      id: 'admin-ob-notifications',
      role: 'admin',
      route: '/notifications',
      selector: '[data-tour="notifications-filters"]',
      title: 'Notificaciones',
      body: 'Bandeja de actividad operativa. Filtra por estado para priorizar pendientes y eventos sin leer.',
      placement: 'bottom',
      mobilePlacement: 'bottom',
    },
    {
      id: 'admin-ob-profile',
      role: 'admin',
      route: '/profile',
      selector: '[data-tour="profile-picture"]',
      title: 'Tu perfil',
      body: 'Actualiza foto, datos de contacto y credenciales. Tu foto aparece en los registros de entrega.',
      placement: 'bottom',
      mobilePlacement: 'bottom',
    },
    {
      id: 'admin-ob-tour-launcher',
      role: 'admin',
      route: '*',
      selector: '[data-tour="tour-launcher"]',
      title: 'Guía contextual',
      body: 'Este botón activa la ayuda específica de la pantalla actual en cualquier momento.',
      placement: 'top',
      mobilePlacement: 'top',
    },
  ],
  supervisor: [
    {
      id: 'supervisor-ob-dashboard',
      role: 'supervisor',
      route: '/supervisor/dashboard',
      selector: '[data-tour="supervisor-dashboard-root"]',
      title: 'Panel supervisor',
      body: 'Estado actual del inventario a tu cargo: activos en stock, asignados, en mantención y dados de baja.',
      placement: 'bottom',
      mobilePlacement: 'bottom',
    },
    {
      id: 'supervisor-ob-trazabilidad',
      role: 'supervisor',
      route: '/supervisor/trazabilidad',
      selector: '[data-tour="supervisor-dashboard-root"]',
      title: 'Trazabilidad',
      body: 'Revisa los movimientos recientes de activos en terreno para validar devoluciones y estado de equipos.',
      placement: 'bottom',
      mobilePlacement: 'bottom',
    },
    {
      id: 'supervisor-ob-notifications',
      role: 'supervisor',
      route: '/notifications',
      selector: '[data-tour="notifications-filters"]',
      title: 'Notificaciones',
      body: 'Bandeja de actividad operativa. Filtra por pendientes para no perder eventos críticos.',
      placement: 'bottom',
      mobilePlacement: 'bottom',
    },
    {
      id: 'supervisor-ob-profile',
      role: 'supervisor',
      route: '/profile',
      selector: '[data-tour="profile-picture"]',
      title: 'Tu perfil',
      body: 'Actualiza tu foto y datos de contacto. Tu firma aparece en actas de entrega y devolución.',
      placement: 'bottom',
      mobilePlacement: 'bottom',
    },
    {
      id: 'supervisor-ob-tour-launcher',
      role: 'supervisor',
      route: '*',
      selector: '[data-tour="tour-launcher"]',
      title: 'Guía contextual',
      body: 'Puedes reabrir la ayuda operativa de la pantalla actual cuando la necesites.',
      placement: 'top',
      mobilePlacement: 'top',
    },
  ],
};
