import type { TourRole, TourStep } from '@alltura/ui';

export const TOUR_VERSION = 'v3';

export const onboardingStepsByRole: Record<TourRole, TourStep[]> = {
  admin: [
    {
      id: 'admin-ob-dashboard',
      role: 'admin',
      route: '/admin/dashboard',
      selector: '[data-tour="admin-dashboard-root"]',
      title: 'Panel operativo',
      body: 'Vista central con KPIs de activos, entregas, devoluciones y firmas. Detecta desviaciones antes de que escalen.',
      placement: 'bottom',
    },
    {
      id: 'admin-ob-dashboard-kpis',
      role: 'admin',
      route: '/admin/dashboard',
      selector: '[data-tour="admin-dashboard-kpis"]',
      title: 'Métricas de inventario',
      body: 'Stock disponible, reservado y registros agotados. Las operaciones pendientes de firma se muestran aquí.',
      placement: 'top',
      mobilePlacement: 'bottom',
    },
    {
      id: 'admin-ob-trazabilidad',
      role: 'admin',
      route: '/admin/trazabilidad',
      selector: '[data-tour="admin-dashboard-root"]',
      title: 'Trazabilidad',
      body: 'Movimientos recientes de stock y activos para auditoría operacional. Misma pantalla, vista enfocada en historial.',
      placement: 'bottom',
      mobilePlacement: 'bottom',
    },
    {
      id: 'admin-ob-users',
      role: 'admin',
      route: '/admin/users',
      selector: '[data-tour="admin-users-root"]',
      title: 'Usuarios del sistema',
      body: 'Gestiona las cuentas con acceso a la plataforma. Asigna roles de administrador o supervisor.',
      placement: 'bottom',
      mobilePlacement: 'bottom',
    },
    {
      id: 'admin-ob-trabajadores',
      role: 'admin',
      route: '/admin/trabajadores',
      selector: '[data-tour="admin-trabajadores-root"]',
      title: 'Trabajadores',
      body: 'Personal interno al que se asignan activos. Los trabajadores no son usuarios del sistema por defecto.',
      placement: 'bottom',
      mobilePlacement: 'bottom',
    },
    {
      id: 'admin-ob-bodegas',
      role: 'admin',
      route: '/admin/ubicacion/bodegas',
      selector: '[data-tour="admin-bodegas-root"]',
      title: 'Bodegas',
      body: 'Ubicaciones físicas donde se almacena el inventario. El stock y los activos se mueven entre bodegas y proyectos.',
      placement: 'bottom',
      mobilePlacement: 'bottom',
    },
    {
      id: 'admin-ob-proyectos',
      role: 'admin',
      route: '/admin/ubicacion/proyectos',
      selector: '[data-tour="admin-proyectos-root"]',
      title: 'Proyectos',
      body: 'Frentes de trabajo a los que se asignan equipos y herramientas. Cada activo rastrea su ubicación actual.',
      placement: 'bottom',
      mobilePlacement: 'bottom',
    },
    {
      id: 'admin-ob-articulos',
      role: 'admin',
      route: '/admin/inventario/articulos',
      selector: '[data-tour="admin-inventory-open-article-modal"]',
      title: 'Catálogo de artículos',
      body: 'Define los tipos de activos: EPP, equipos y herramientas. Cada artículo puede tener múltiples unidades físicas.',
      placement: 'bottom',
      mobilePlacement: 'bottom',
    },
    {
      id: 'admin-ob-epp',
      role: 'admin',
      route: '/admin/inventario/epp',
      selector: '[data-tour="admin-inventory-epp"]',
      title: 'Inventario EPP',
      body: 'Elementos de protección personal por unidad. Cada activo tiene código único, estado y trazabilidad completa.',
      placement: 'bottom',
      mobilePlacement: 'bottom',
    },
    {
      id: 'admin-ob-equipos',
      role: 'admin',
      route: '/admin/inventario/equipos',
      selector: '[data-tour="admin-inventory-equipos"]',
      title: 'Inventario Equipos',
      body: 'Equipos de trabajo con seguimiento individual: asignación, custodia, mantención y baja controlada.',
      placement: 'bottom',
      mobilePlacement: 'bottom',
    },
    {
      id: 'admin-ob-herramientas',
      role: 'admin',
      route: '/admin/inventario/herramientas',
      selector: '[data-tour="admin-inventory-herramientas"]',
      title: 'Inventario Herramientas',
      body: 'Herramientas manuales y eléctricas. Mismo flujo que EPP y equipos: entrega, devolución, estado y ubicación.',
      placement: 'bottom',
      mobilePlacement: 'bottom',
    },
    {
      id: 'admin-ob-activo-demo',
      role: 'admin',
      route: '/admin/inventario/epp',
      selector: '[data-tour="admin-inventory-grid"]',
      title: 'Perfil de activo',
      body: 'Cada tarjeta abre el perfil completo del activo: historial, acciones de entrega, firma digital y descarga de ficha PDF.',
      placement: 'top',
      mobilePlacement: 'bottom',
      demoAction: 'open-activo-demo',
    },
    {
      id: 'admin-ob-notifications',
      role: 'admin',
      route: '/notifications',
      selector: '[data-tour="notifications-filters"]',
      title: 'Notificaciones',
      body: 'Bandeja de actividad operativa. Filtra por estado para priorizar pendientes y eventos sin leer.',
      placement: 'bottom',
      mobilePlacement: 'bottom',
    },
    {
      id: 'admin-ob-profile',
      role: 'admin',
      route: '/profile',
      selector: '[data-tour="profile-picture"]',
      title: 'Tu perfil',
      body: 'Actualiza foto, datos de contacto y credenciales. Tu foto aparece en los registros de entrega.',
      placement: 'bottom',
      mobilePlacement: 'bottom',
    },
    {
      id: 'admin-ob-tour-launcher',
      role: 'admin',
      route: '*',
      selector: '[data-tour="tour-launcher"]',
      title: 'Guía contextual',
      body: 'Este botón activa la ayuda específica de la pantalla actual en cualquier momento.',
      placement: 'top',
      mobilePlacement: 'top',
    },
  ],
  supervisor: [
    {
      id: 'supervisor-ob-dashboard',
      role: 'supervisor',
      route: '/supervisor/dashboard',
      selector: '[data-tour="supervisor-dashboard-root"]',
      title: 'Panel supervisor',
      body: 'Estado actual del inventario a tu cargo: activos en stock, asignados, en mantención y dados de baja.',
      placement: 'bottom',
      mobilePlacement: 'bottom',
    },
    {
      id: 'supervisor-ob-trazabilidad',
      role: 'supervisor',
      route: '/supervisor/trazabilidad',
      selector: '[data-tour="supervisor-dashboard-root"]',
      title: 'Trazabilidad',
      body: 'Revisa los movimientos recientes de activos en terreno para validar devoluciones y estado de equipos.',
      placement: 'bottom',
      mobilePlacement: 'bottom',
    },
    {
      id: 'supervisor-ob-notifications',
      role: 'supervisor',
      route: '/notifications',
      selector: '[data-tour="notifications-filters"]',
      title: 'Notificaciones',
      body: 'Bandeja de actividad operativa. Filtra por pendientes para no perder eventos críticos.',
      placement: 'bottom',
      mobilePlacement: 'bottom',
    },
    {
      id: 'supervisor-ob-profile',
      role: 'supervisor',
      route: '/profile',
      selector: '[data-tour="profile-picture"]',
      title: 'Tu perfil',
      body: 'Actualiza tu foto y datos de contacto. Tu firma aparece en actas de entrega y devolución.',
      placement: 'bottom',
      mobilePlacement: 'bottom',
    },
    {
      id: 'supervisor-ob-tour-launcher',
      role: 'supervisor',
      route: '*',
      selector: '[data-tour="tour-launcher"]',
      title: 'Guía contextual',
      body: 'Puedes reabrir la ayuda operativa de la pantalla actual cuando la necesites.',
      placement: 'top',
      mobilePlacement: 'top',
    },
  ],
};
